name: LEGACY Build and Push

on:
  push:
    branches:
      - $default-branch

permissions:
  contents: write
  id-token: write
  pages: write
  checks: write
  statuses: write

jobs:
  build-and-push:
    uses: legalzoom/gha-workflows/.github/workflows/docker-build-and-push-legacy-api.yaml@main
    with:
      # TODO: Can we infer image-name? Do we need to pass inputs for these? Can we remove tests, since it's already merged?
      image-name: engineering/orderservice-gha
      runs-on: ${{ github.repo }}-arm64
      source-folder: ./src/OrderService
      test-folder: ./src/Tests/Test.Order

  deploy-to-k8s-dev:
    name: Deploy to Kubernetes
    needs: [build-and-push]
    uses: legalzoom/gha-workflows/.github/workflows/deploy-to-k8s.yaml@main
    with:
      image-tag: ${{ github.sha }}
      image-names: "image_name_gha"
      stage-name: "dev"
      runs-on: ${{ github.repo }}

  deploy-to-k8s-qa:
    name: Deploy to Kubernetes
    needs: [build-and-push]
    uses: legalzoom/gha-workflows/.github/workflows/deploy-to-k8s.yaml@main
    with:
      image-tag: ${{ github.sha }}
      image-names: "image_name_gha"
      stage-name: "qa"
      runs-on: ${{ github.repo }}

  manual-approval:
    name: Manual Approval for Production
    needs: [deploy-to-k8s-qa]
    runs-on: ${{ github.repo }}
    steps:
      - name: Wait for manual approval
        run: |
          echo "Waiting for manual approval..."
    environment:
      name: prd

  deploy-to-k8s-prd:
    name: Deploy to Kubernetes
    needs: [manual-approval]
    uses: legalzoom/gha-workflows/.github/workflows/deploy-to-k8s.yaml@main
    with:
      image-tag: ${{ github.sha }}
      image-names: "image_name_gha"
      stage-name: "prd"
      runs-on: ${{ github.repo }}
